# Assignment-3

Question:  
         Write a program then use some numpy functions or method in it.

In [ ]:
import numpy as np; #import numpy

In [ ]:
# arange function
np_arr1=np.arange(1,100,10) # arange return a vector or 1D array with stopValue-1 number of element
# np.arange(startValue,stopValue,steps or leave element how we want )
print("Array with Arange method: ",np_arr1)



In [ ]:
# linspace function or method
np_arr2=np.linspace(100,150,2) # linspace(start, stop, how many element want in array)
print("Array with linspace method:",np_arr2)

In [ ]:
# reshape method 
np_arr3=np.arange(1,21) # create a vector
print("Vector is: ",np_arr3)

reshapeArray=np.reshape(np_arr3,(2,10)) # convert the shape of vector into matrix
print(f"Reshape Array is:{reshapeArray}")



flattenArray=reshapeArray.flatten() # convert matrix into vector  , work with copy of the original array 
revalArray=reshapeArray.ravel() # convert matrix into vector , work with original array

print(f"Flatten Array:{flattenArray}\nReval Array:{revalArray}")



transpose=reshapeArray.T # take transpose using T property
print(f"Transpose: {transpose}")

# Assignment-4

Question:
        Perform some mathematical operations on matrices

In [ ]:
# create two matrix 
matrixA=np.arange(1,13).reshape(3,4)
matrixB=np.arange(13,25).reshape(3,4)

print(f"Matrix A:\n{matrixA}\nMatrix B:\n{matrixB}") # print both matrix

### Addition of two matrix

In [ ]:
additionOfMatrix=np.add(matrixA,matrixB)
print(f"Addition of tow matrix is:\n{additionOfMatrix}")

### Subtraction of tow matrix

In [ ]:
subtractionOfMatrix=np.subtract(matrixB,matrixA)
print(f"Subtraction of tow matrix is:\n{subtractionOfMatrix}")

### Multiplication of tow matrix

In [ ]:
# Method-1
multiplicationOfMatrix=np.multiply(matrixA,matrixB)
print(f"Multiplication of tow matrix is:\n{multiplicationOfMatrix}")
# Method-2
# print("matrixA * matrixB",matrixA@matrixB) # show error

### Division of Matrix

In [ ]:
divisionOfMatrix=np.divmod(matrixB,matrixA)
print(f"Multiplication of tow matrix is:\n{divisionOfMatrix}")

### Min and Max Value in Matrix

In [ ]:
print(matrixA)
print(f"Min Element in Matrix A:{matrixA.min()}\nMax Element in Matrix A:{matrixA.max()}") 
print(f"Max  Column  in Matrix A:{matrixA.max(axis=0)}\n Min  Row in Matrix A:{matrixA.max(axis=1)}")

### Sum operation 

In [ ]:
sumOfMatrix=np.sum(matrixA)
print(f"Sum of all element of matrix A:{sumOfMatrix}")


sumOfSingleRow=np.sum(matrixA,axis=1)
print(f"Sum of Single Row of Matrix A:{sumOfSingleRow}")



sumOfSingleCol=np.sum(matrixA,axis=0)
print(f"Sum of Single Col of Matrix A:{sumOfSingleCol}")

# Assignment-5

## Slicing  and Indexing of Matrix
### Create a 4x4 matrix

In [ ]:
np_arr4=np.arange(1,17).reshape(4,4)
print(f"4*4 Array is: {np_arr4}")

In [26]:
#Indexing
print(f"Specific Element: {np_arr4[2,1]}") # return 10 becasue M21 is 10
print(f"0th element is:{np_arr4[0,0]}")
print(f"Specific column:{np_arr4[:,1]}")
print(f"specific row:{np_arr4[1:2]}")

# To print orignal Matrix
print(f"Original Matrix: {np_arr4}")
print(f"Original Matrix: {np_arr4[:]}")
print(f"Original Matrix: {np_arr4[:,:]}")


Specific Element: 10
0th element is:1
Specific column:[ 2  6 10 14]
specific row:[[5 6 7 8]]
Original Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Original Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Original Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### Q:1 Print the first column of a 4x4 matrix vertically.
#### Q:2 Print the last column of a 4x4 matrix vertically.
#### Q:3 Print second and third column of a matrix.

In [27]:
print("First column of a 4x4 matrix:",np_arr4[:,0])
print("Last Column of a 4x4 matrix:",np_arr4[:,-1])
print("Second and thrid Column:",np_arr4[:,1:3])

First column of a 4x4 matrix: [ 1  5  9 13]
Last Column of a 4x4 matrix: [ 4  8 12 16]
Second and thrid Column: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
