# Assignment-3

Question:  
         Write a program then use some numpy functions or method in it.

In [2]:
import numpy as np; #import numpy

In [ ]:
# arange function
np_arr1=np.arange(1,100,10) # arange return a vector or 1D array with stopValue-1 number of element
# np.arange(startValue,stopValue,steps or leave element how we want )
print("Array with Arange method: ",np_arr1)



In [ ]:
# linspace function or method
np_arr2=np.linspace(100,150,2) # linspace(start, stop, how many element want in array)
print("Array with linspace method:",np_arr2)

In [ ]:
# reshape method 
np_arr3=np.arange(1,21) # create a vector
print("Vector is: ",np_arr3)

reshapeArray=np.reshape(np_arr3,(2,10)) # convert the shape of vector into matrix
print(f"Reshape Array is:{reshapeArray}")



flattenArray=reshapeArray.flatten() # convert matrix into vector  , work with copy of the original array 
revalArray=reshapeArray.ravel() # convert matrix into vector , work with original array

print(f"Flatten Array:{flattenArray}\nReval Array:{revalArray}")



transpose=reshapeArray.T # take transpose using T property
print(f"Transpose: {transpose}")

# Assignment-4

Question:
        Perform some mathematical operations on matrices

In [4]:
# create two matrix 
matrixA=np.arange(1,13).reshape(3,4)
matrixB=np.arange(13,25).reshape(3,4)

print(f"Matrix A:\n{matrixA}\nMatrix B:\n{matrixB}") # print both matrix

Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix B:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


### Addition of two matrix

In [ ]:
additionOfMatrix=np.add(matrixA,matrixB)
print(f"Addition of tow matrix is:\n{additionOfMatrix}")

### Subtraction of tow matrix

In [6]:
subtractionOfMatrix=np.subtract(matrixB,matrixA)
print(f"Subtraction of tow matrix is:\n{subtractionOfMatrix}")

Subtraction of tow matrix is:
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
