# Assignment-3

Question:  
         Write a program then use some numpy functions or method in it.

In [ ]:
import numpy as np; #import numpy

In [ ]:
# arange function
np_arr1=np.arange(1,100,10) # arange return a vector or 1D array with stopValue-1 number of element
# np.arange(startValue,stopValue,steps or leave element how we want )
print("Array with Arange method: ",np_arr1)



In [ ]:
# linspace function or method
np_arr2=np.linspace(100,150,2) # linspace(start, stop, how many element want in array)
print("Array with linspace method:",np_arr2)

In [ ]:
# reshape method 
np_arr3=np.arange(1,21) # create a vector
print("Vector is: ",np_arr3)

reshapeArray=np.reshape(np_arr3,(2,10)) # convert the shape of vector into matrix
print(f"Reshape Array is:{reshapeArray}")



flattenArray=reshapeArray.flatten() # convert matrix into vector  , work with copy of the original array 
revalArray=reshapeArray.ravel() # convert matrix into vector , work with original array

print(f"Flatten Array:{flattenArray}\nReval Array:{revalArray}")



transpose=reshapeArray.T # take transpose using T property
print(f"Transpose: {transpose}")

# Assignment-4

Question:
        Perform some mathematical operations on matrices

In [ ]:
# create two matrix 
matrixA=np.arange(1,13).reshape(3,4)
matrixB=np.arange(13,25).reshape(3,4)

print(f"Matrix A:\n{matrixA}\nMatrix B:\n{matrixB}") # print both matrix

### Addition of two matrix

In [ ]:
additionOfMatrix=np.add(matrixA,matrixB)
print(f"Addition of tow matrix is:\n{additionOfMatrix}")

### Subtraction of tow matrix

In [ ]:
subtractionOfMatrix=np.subtract(matrixB,matrixA)
print(f"Subtraction of tow matrix is:\n{subtractionOfMatrix}")

### Multiplication of tow matrix

In [ ]:
# Method-1
multiplicationOfMatrix=np.multiply(matrixA,matrixB)
print(f"Multiplication of tow matrix is:\n{multiplicationOfMatrix}")
# Method-2
# print("matrixA * matrixB",matrixA@matrixB) # show error

Multiplication of tow matrix is:
[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]


### Division of Matrix

In [ ]:
divisionOfMatrix=np.divmod(matrixB,matrixA)
print(f"Multiplication of tow matrix is:\n{divisionOfMatrix}")

array([[13.        ,  7.        ,  5.        ,  4.        ],
       [ 3.4       ,  3.        ,  2.71428571,  2.5       ],
       [ 2.33333333,  2.2       ,  2.09090909,  2.        ]])

### Min and Max Value in Matrix

In [ ]:
print(matrixA)
print(f"Min Element in Matrix A:{matrixA.min()}\nMax Element in Matrix A:{matrixA.max()}") 
print(f"Max  Column  in Matrix A:{matrixA.max(axis=1)}\n Min  Row in Matrix A:{matrixA.max(axis=0)}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Min Element in Matrix A:1
Max Element in Matrix A:12
Max  Row  in Matrix A:[ 4  8 12]
 Min  Column in Matrix A:[ 9 10 11 12]


### Sum operation 

In [ ]:
sumOfMatrix=np.sum(matrixA)
print(f"Sum of all element of matrix A:{sumOfMatrix}")